version: '3.8'

services:
  app:
    user: 1000:1000
    container_name: backend-${PROJECT_NAME}
    build: .
    ports:
      - 3000:3000
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/app
      - app_data:/app/src/data
      - node_modules:/app/node_modules
    networks:
      - observability

  db:
    container_name: postgres-${PROJECT_NAME}
    image: postgres:11
    restart: unless-stopped
    ports:
      - 5433:5433
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    networks:
      - observability

volumes:
  node_modules:
  app_data:

networks:
  observability:
    external: true
